name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: ls
    - run: nix-build - A regolith-ilia
    - run: nix-build - A regolith-rofication
    - run: nix-build - A regolith-remontoire
    - run: nix-build - A regolith-powerd
    - run: nix-build - A regolith-inputd
    - run: nix-build - A regolith-disiplayd
    - run: nix-build 

    
    
